name: base
dependencies:
  - anaconda::python=3.10
  - anaconda::numpy
  - anaconda::pyyaml
  - conda-forge::chess
  - conda-forge::backoff
  - anaconda::pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch
    - Flask=3.0.3
    - flask-cors
    - gunicorn=23.0.0
    - Werkzeug=3.0.3
    - celery
    - requests
    - mod_wsgi
